# Generated by Django 3.1 on 2020-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_auto_20200816_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
