# Generated by Django 3.1 on 2020-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0003_auto_20200816_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='availability',
            field=models.DateTimeField(blank=True),
        ),
    ]
