# Generated by Django 3.1 on 2020-08-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0004_auto_20200816_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='accountant',
            name='hour_rate',
        ),
    ]
