# Generated by Django 3.1 on 2020-08-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0005_auto_20200816_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountant',
            name='hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
